services:
  nginx:
    image: nginx:1.27-alpine
    container_name: air_pollution_app_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  backend:
    image: ghcr.io/miranas/air_pollution_app:latest
    container_name: air_pollution_app
    restart: always
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  
  redis:
    image: redis:7.2-alpine
    container_name: air_pollution_app__redis
    restart: always
    expose:
      - "6379"
      

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: air_pollution_app_prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      # bind mount, file mapping
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: air_pollution_app_grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: air_pollution_app_portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  frontend:
    image: ghcr.io/miranas/air_pollution_app_ui:latest
    restart: always
    expose:
      - "8501"
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:5000/api/latest}
      - APP_COMMIT_SHA=${APP_COMMIT_SHA:-local-dev}
    depends_on:
      - backend
    
# create volumes
volumes:
  prometheus_data:
  grafana_data:
  portainer_data:






    


    



